version: '3.8'

services:
  app:
    build: .
    container_name: ci-cd-summative-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/ci-cd-summative
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: ci-cd-summative-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
